### ISSUE TITLE
Fix port to Python 3

### ISSUE THREAD

**Issue by pabramowicz** [ClearcodeHQ/querystringsafe_base64#15]
In Python 3 `querystringsafe_base64.decode(base64.b64encode(b'not compressed contents'))` 
returns `TypeError: encoding or errors without a string argument` instead of `zlib.error`

 Possible solution: `return urlsafe_b64ddecode(encoded).replace(b'-', b'=')` for Python 3 in `decode`.

**Comment by fizyk** [comment]
@pabramowicz is this still an issue?
